version: "3"

services:
  app:
    build: .
    networks:
      - kafka_broker-kafka
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  rabbitmq:
    image: rabbitmq:3.8.16-management
    networks:
      - kafka_broker-kafka
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  postgres:
    image: "postgres"
    networks:
      - kafka_broker-kafka
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  pgadmin-compose:
    image: dpage/pgadmin4
    networks:
      - kafka_broker-kafka
    environment:
      PGADMIN_DEFAULT_EMAIL: "jp@newtec.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  kafka_broker-kafka:
    external: true